/**
 * MockDataProvider – centralised loader for all mock / demo data.
 *
 * Every JSON file generated by gen_mock_data.py is loaded once at import time
 * and re-exported as a typed constant so that individual services can simply
 * import what they need without touching the file system at runtime.
 */

import { join } from "path"
import { readFileSync } from "fs"

// ─── Resolve base path (works both in dev and packaged app) ─────────────────
function resolveMockDir(): string {
  // In development: out/main/mock-data/
  // In production (packaged): the copyMockDataPlugin copies JSON files to out/main/mock-data/
  return join(__dirname, "mock-data")
}

function loadJSON<T>(fileName: string): T {
  const filePath = join(resolveMockDir(), fileName)
  const raw = readFileSync(filePath, "utf-8")
  return JSON.parse(raw) as T
}

// ─── Type imports ───────────────────────────────────────────────────────────
import type { Agent } from "../../shared/types/agent"
import type { Skill } from "../../shared/types/skill"
import type { InstalledPlugin } from "../../shared/types/plugin"
import type { Command } from "../../shared/types/command"
import type { HookDefinition } from "../../shared/types/hook"
import type { MCPServer } from "../../shared/types/mcp"
import type { Settings } from "../../shared/types/settings"
import type { MarketplaceSource, MarketplacePlugin } from "../../shared/types/marketplace"
import type {
  AnalyticsData,
  ActivityDay,
  WrappedData,
  ParsedSession,
} from "../../shared/types/session-detail"

// ─── Plan types (inline, not in shared/types) ──────────────────────────────
export interface MockPlanInfo {
  fileName: string
  content: string
}

// ─── Project types (inline, mirrors ProjectDiscoveryService) ────────────────
export interface MockProjectSession {
  sessionId: string
  projectDir: string
  jsonlFile: string
  isActive: boolean
  lastModified: string
}
export interface MockProjectInfo {
  projectDir: string
  projectName: string
  agentCount: number
  activeCount: number
  lastActivity: string
  sessions: MockProjectSession[]
}

// ─── Office agent type ──────────────────────────────────────────────────────
export interface MockOfficeAgent {
  id: number
  sessionId: string
  projectDir: string
  jsonlFile: string
  isActive: boolean
  lastModified: string
}

// ─── Project config types ───────────────────────────────────────────────────
export interface MockProjectConfig {
  agents: Array<Agent & { projectDir: string }>
  skills: Array<Skill & { projectDir: string }>
  mcpServers: Array<MCPServer & { projectDir: string }>
  plans: Array<{
    name: string
    content: string
    filePath: string
    projectDir: string
    lastModified: string
  }>
  hooks: unknown[]
  commands: unknown[]
  summary: {
    agentCount: number
    skillCount: number
    mcpCount: number
    planCount: number
    hookCount: number
    commandCount: number
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Lazy-loaded singletons
// ═══════════════════════════════════════════════════════════════════════════════

let _agents: Agent[] | null = null
let _skills: { personal: Skill[]; plugin: Skill[] } | null = null
let _plugins: InstalledPlugin[] | null = null
let _commands: Command[] | null = null
let _hooks: HookDefinition[] | null = null
let _mcpServers: MCPServer[] | null = null
let _settings: Settings | null = null
let _plans: MockPlanInfo[] | null = null
let _analytics: Record<string, AnalyticsData> | null = null
let _heatmap: ActivityDay[] | null = null
let _wrapped: WrappedData | null = null
let _projects: MockProjectInfo[] | null = null
let _sessionDetails: Record<string, ParsedSession> | null = null
let _officeAgents: Record<string, MockOfficeAgent[]> | null = null
let _projectConfigs: Record<string, MockProjectConfig> | null = null
let _marketplaceSources: MarketplaceSource[] | null = null
let _marketplacePlugins: Record<string, MarketplacePlugin[]> | null = null

export const MockData = {
  get agents(): Agent[] {
    if (!_agents) {
      _agents = loadJSON<Agent[]>("agents.json")
      // Ensure filePath is set
      _agents = _agents.map((a) => ({
        ...a,
        filePath: `/mock/agents/${a.name}.md`,
      }))
    }
    return _agents
  },

  get skills(): { personal: Skill[]; plugin: Skill[] } {
    if (!_skills) {
      const raw = loadJSON<{ personal: Omit<Skill, "source" | "filePath">[]; plugin: Omit<Skill, "source" | "filePath">[] }>("skills.json")
      _skills = {
        personal: raw.personal.map((s) => ({
          ...s,
          source: "personal" as const,
          filePath: `/mock/skills/${s.name}/SKILL.md`,
          hasReference: s.hasReference ?? false,
          hasTemplates: s.hasTemplates ?? false,
        })),
        plugin: raw.plugin.map((s) => ({
          ...s,
          source: "plugin" as const,
          filePath: `/mock/skills/${s.name}/SKILL.md`,
          hasReference: s.hasReference ?? false,
          hasTemplates: s.hasTemplates ?? false,
        })),
      }
    }
    return _skills
  },

  get plugins(): InstalledPlugin[] {
    if (!_plugins) _plugins = loadJSON<InstalledPlugin[]>("plugins.json")
    return _plugins
  },

  get commands(): Command[] {
    if (!_commands) _commands = loadJSON<Command[]>("commands.json")
    return _commands
  },

  get hooks(): HookDefinition[] {
    if (!_hooks) _hooks = loadJSON<HookDefinition[]>("hooks.json")
    return _hooks
  },

  get mcpServers(): MCPServer[] {
    if (!_mcpServers) _mcpServers = loadJSON<MCPServer[]>("mcp-servers.json")
    return _mcpServers
  },

  get settings(): Settings {
    if (!_settings) _settings = loadJSON<Settings>("settings.json")
    return _settings
  },

  get plans(): MockPlanInfo[] {
    if (!_plans) _plans = loadJSON<MockPlanInfo[]>("plans.json")
    return _plans
  },

  getAnalytics(timeRange: string): AnalyticsData {
    if (!_analytics) {
      _analytics = {
        "7d": loadJSON<AnalyticsData>("analytics-7d.json"),
        "30d": loadJSON<AnalyticsData>("analytics-30d.json"),
        "90d": loadJSON<AnalyticsData>("analytics-90d.json"),
        "year": loadJSON<AnalyticsData>("analytics-year.json"),
      }
    }
    return _analytics[timeRange] ?? _analytics["30d"]
  },

  get heatmap(): ActivityDay[] {
    if (!_heatmap) _heatmap = loadJSON<ActivityDay[]>("heatmap.json")
    return _heatmap
  },

  get wrapped(): WrappedData {
    if (!_wrapped) _wrapped = loadJSON<WrappedData>("wrapped.json")
    return _wrapped
  },

  get projects(): MockProjectInfo[] {
    if (!_projects) _projects = loadJSON<MockProjectInfo[]>("projects.json")
    return _projects
  },

  get sessionDetails(): Record<string, ParsedSession> {
    if (!_sessionDetails)
      _sessionDetails = loadJSON<Record<string, ParsedSession>>("session-details.json")
    return _sessionDetails
  },

  get officeAgents(): Record<string, MockOfficeAgent[]> {
    if (!_officeAgents)
      _officeAgents = loadJSON<Record<string, MockOfficeAgent[]>>("office-agents.json")
    return _officeAgents
  },

  get projectConfigs(): Record<string, MockProjectConfig> {
    if (!_projectConfigs)
      _projectConfigs = loadJSON<Record<string, MockProjectConfig>>("project-configs.json")
    return _projectConfigs
  },

  get marketplaceSources(): MarketplaceSource[] {
    if (!_marketplaceSources)
      _marketplaceSources = loadJSON<MarketplaceSource[]>("marketplace-sources.json")
    return _marketplaceSources
  },

  get marketplacePlugins(): Record<string, MarketplacePlugin[]> {
    if (!_marketplacePlugins)
      _marketplacePlugins = loadJSON<Record<string, MarketplacePlugin[]>>("marketplace-plugins.json")
    return _marketplacePlugins
  },
}
